---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: nodejs-kub
   labels:
      app: nodejs-kub-label
 spec:
   replicas: 2
   selector: 
      matchLabels:
         app: nodejs-temp
   template:
     metadata:
       labels:
         app: nodejs-temp
     spec:
       containers:
         - name: nodejs-con
           image: sandkar/test-node-image:0.0.1
           ports:
             - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-temp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-nodeport
spec:
  selector:
    app: nodejs-temp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
      nodePort: 30000