---
 apiVersion: app/v1
 kind: Deployment
 metadata:
   name: nodejs-kub
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: nodejs-temp
     spec:
       containers:
         - name: nodejs-con
           image: sandkar/test-node-image:0.0.1
           ports:
             - containerPort: 8080